name: lambda-deployment-with-github-action-test

on:
  push:
    branches: master # You can use any of your root or master branch name

jobs: #Workflow run is made up of one or more jobs
  deploy_lambda:
    runs-on: ubuntu-latest #Through which Server OS we need to Work (type of machine to run the job on)
    steps:
      #Using versioned actions
      - uses: actions/checkout@v3 # --> Reference a specific version
      - uses: actions/setup-node@v3 # --> To Setup the Server With Node Env
        with:
          node-version: '14' #--> Specify the Version of the Node
      - name: Install serverless globally
        run: npm install -g serverless

      - name: Install NestJS
        run: npm i -g @nestjs/cli

      - name: Configure serverless authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install npm dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          file_name: .env

      - name: Deploy lambda function
        run: sls deploy
